# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuLoop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuLoop

  target 'ChuLoopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChuLoopUITests' do
    # Pods for testing
  end

  # Alamofire
  pod 'Alamofire' , '5.10.2'

  # Google Login
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'

  # Naver Login
  pod 'naveridlogin-sdk-ios'

  # KaKao Login
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKUser'

end
